### ISSUE TITLE
~/.local/share/rizin vs ~/.local/share/RizinOrg

### ISSUE THREAD

**Issue by s0i37** [rizinorg/rz-ghidra#183]
I just have installed rz-ghidra.
The `make install` copyed files in `~/.local/share/rizin/plugins/` dir.
But `cutter` looking for plugins in `~/.local/share/RizinOrg/Cutter/plugins` folder.
WTF
That's actually difference between these folder? May I create symlink between it to solving this confusion?

**Comment by karliss** [comment]
You are probably confused by rizin plugin and Cutter plugin. Those are two separate things. Didn't verify by building but from looking at the buildsytem config files share/rizin/plugins is default install location for rizin plugin and share/RizinOrg/Cutter/plugins so everything looks correct so far. Did you enable compilation of Cutter plugin as described in [build instructions](https://github.com/rizinorg/cutter/issues/1708) ?

As a side note for help on questions like this that are likely  a misconfiguration problem prefer asking in mattermost/irc/telegram channels first instead of creating github issue.

**Comment by s0i37** [comment]
`~/.local/share/rizin` - rizin
`~/.local/share/RizinOrg` - cutter
I've found my mistake. I forgot to specify BUILD_CUTTER_PLUGIN.
The right command:
`cmake -DBUILD_CUTTER_PLUGIN=ON -DCUTTER_SOURCE_DIR=~/src/cutter -DCMAKE_INSTALL_PREFIX=~/.local ..`
